name: Build & push

on:
  push:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

concurrency:
    group: main
    cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jhginn
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: set tag
        run: |
            echo "TAG=$(date +%F | tr -d '-')" >> $GITHUB_ENV
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jhginn/cloud-run-mcp-proxy:${{ env.LATEST_TAG }}, jhginn/cloud-run-mcp-proxy:${{ env.TAG }}
